//
//  EnglishStrings.swift
//  selfManager
//
//  Created by Assistant on 2024
//

import Foundation

// 英文字符串资源
struct EnglishStrings {
    static let strings: [String: String] = [
        // 通用
        "settings": "Settings",
        "done": "Done",
        "cancel": "Cancel",
        "save": "Save",
        "delete": "Delete",
        "edit": "Edit",
        "back": "Back",
        "close": "Close",
        
        // 设置页面
        "appearance": "Appearance",
        "dark_mode": "Dark Mode",
        "language": "Language",
        "language_selection": "Language Selection",
        "home_cards": "Home Cards Display",
        "asset_card": "Asset Card",
        "habit_card": "Habit Card",
        "achievement_card": "Achievement Card",
        "anxiety_card": "Anxiety Card",
        "pinned_subtask_card": "Pinned Subtasks Card",
        "appearance_light": "Light",
        "appearance_dark": "Dark",
        "appearance_system": "System",
        "help_feedback": "Help & Feedback",
        "expiration_time": "Expiration",
        "add_goal": "Add Goal",
        "add_contact": "Add Contact",
        "recent_records": "Recent Records",
        "iCloud_sync": "iCloud Sync",
        "icloud_available": "iCloud Available",
        "icloud_unavailable": "iCloud Unavailable",
        "refresh": "Refresh",
        "syncing": "Syncing…",
        "last_sync": "Last Sync",
        "sync_now": "Sync Now",
        "app_update": "App Update",
        "check_update": "Check Update",
        "new_version_available": "New Version Available",
        "current_version": "Current Version",
        "latest_version": "Latest Version",
        "update": "Update",
        "later": "Later",
        "up_to_date": "Already up to date",
        "already_latest_version": "Already up to date",
        
        // 其他页面标题
        "home": "Home",
        "goals": "Goals",
        "records": "Records",
        "contacts": "Contacts",
        "habits": "Habit Center",
        "achievements": "Achievement Center",
        "tags": "Tag Management",
        "user_info": "My Profile",
        "my_info": "My Info",
        "username_label": "Username:",
        "username_placeholder": "Enter username",
        "name_placeholder": "Enter name",
        "avatar_label": "Avatar:",
        "personal_description_label": "Description:",
        "personal_description_placeholder": "Enter description",
        "note_placeholder": "Enter notes",
        "company": "Company",
        "company_placeholder": "Enter company name",
        "position": "Position",
        "position_placeholder": "Enter position",
        "phone": "Phone",
        "email": "Email",
        "address": "Address",
        "recent_moods": "Recent Moods",
        "custom_info": "Custom Info",
        "custom_info_footer": "Add arbitrary key-value info. Shown on Home info cards; overflow is hidden.",
        "name_label": "Name",
        "info_label": "Info",
        "add_field": "Add Field",
        
        // 标签相关
        "tag_management": "Tag Management",
        "tag_detail": "Tag Detail",
        "tag_category": "Tag Categories",
        "tag_category_detail": "Category Detail",
        "search_tags_placeholder": "Search tags",
        "system": "System",
        "manage": "Manage",
        "add_new_tag_title": "Add New Tag",
        "tag_name_label": "Tag Name",
        "tag_name_placeholder": "Enter tag name",
        "tag_description_optional_label": "Tag Description (optional)",
        "tag_description_placeholder": "Enter tag description",
        "add_tag_action": "Add Tag",
        "no_description": "No description",
        "description_optional": "Description (optional)",
        "category": "Category",
        "no_category": "No category",
        "manage_categories": "Manage Categories",
        "color": "Color",
        "system_built_in_tag": "System built-in tag",
        "alert_info_title": "Info",
        "delete_tag_title": "Delete Tag",
        "delete_tag_confirm_before": "Are you sure to delete tag \"",
        "delete_tag_confirm_after": "\"? This will remove the tag from all related items.",
        "save_failed": "Save Failed",
        "confirm_delete": "Confirm Delete",
        "delete_category": "Delete Category",
        "delete_category_confirm_before": "Are you sure to delete category \"",
        "delete_category_confirm_after": "\"? This action cannot be undone.",
        "category_name": "Category Name",
        "category_name_placeholder": "Enter category name",
        "category_description_optional": "Category Description (optional)",
        "category_description_placeholder": "Enter category description",
        "add_tag_category": "Add Tag Category",
        "personal": "Personal",
        "edit_tag_title": "Edit Tag",
        "preview": "Preview",
        "ok": "OK",
        "tag_name_empty": "Tag name cannot be empty",
        "search_or_create_tag_placeholder": "Enter tag name to search or create",
        "tag_name_too_long": "Tag name should be at most 32 characters",
        "tag_name_is_built_in": "This tag is system built-in, please select from the list",
        "tag_already_exists": "Tag already exists, please select from the list",
        "create_and_add": "Create and Add",
        "existing": "Existing",
        "tag_category_management": "Tag Category Management",
        "all_categories": "All",
        // Sidebar Tags Card
        "all_tags_title": "All Tags",
        "all_tags_count_prefix": "Total ",
        "all_tags_count_suffix": " tags",
        "create_goal_or_contact_add_tag_hint": "Add tags when creating goals or contacts",
        "more_tags_prefix": "More ",
        "more_tags_suffix": " tags",
        
        // 提示信息
        "language_changed": "Language Changed",
        "restart_required": "Some changes may require restarting the app to take full effect",
    
        // 联系人分段
        "contacts_all": "All",
        "contacts_family": "Family",
        "contacts_friend": "Close Friends",
        "contacts_work": "Work",
        "contacts_role_model": "Role Models",
        "contacts_other": "Others",
        "contacts_useful": "Useful",

        // 菜单与筛选
        "list_view": "List View",
        "gallery_view": "Card View",
        "category_time": "Time",
        "category_type": "Type",
        "sort": "Sort",
        "sort_name": "Name",
        "sort_create_time": "Created Time",
        "sort_modify_time": "Modified Time",
        "sort_visit_time": "Contact Time",
        "recycle_bin": "Recycle Bin",
        "empty_trash": "Empty Trash",

        // 搜索与空状态
        "search_contacts_placeholder": "Search contacts",
        "empty_no_contacts": "No contacts yet",
        "empty_no_matches": "No matching contacts",
        "add_first_contact": "Add your first contact",
        // Record editor
        "record_editor_placeholder": "Write down your thoughts...",

        // 目标详情常用字段
        "due_date": "Due Date",
        "subtasks": "Subtasks",
        "add": "Add",
        "no_subtasks": "No subtasks",
        "parent_goal": "Parent Goal",
        "goal_not_found": "Goal not found",
        "unknown_goal": "Unknown goal",
        "priority": "Priority",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "progress": "Progress",
        "goal_type": "Goal Type",
        "goal_name": "Goal Name",
        "goal_name_placeholder": "Enter goal name",
        "goal_description": "Goal Description",
        "goal_description_placeholder": "Enter goal description (optional)",
        "goal_type_life": "Life Goals",
        "goal_type_yearly": "Yearly Goals",
        "goal_type_short_term": "Short-term Goals",
        "goal_type_habit": "Habits",
        "all": "All",
        "goal_relation": "Goal Relations",
        "add_task": "Add Task",
        "related_person": "Related Person",
        "select": "Select",
        "no_related_contact": "No related contact",
        "background_image": "Background Image",
        "default": "Default",
        "view_activity": "View Activity",
        "delete_goal": "Delete Goal",
        "move_to_trash": "Move to Recycle Bin",

        // 联系人详情字段
        "basic_info": "Basic Info",
        "contact_info": "Contact Info",
        "classification_info": "Classification",
        "other_info": "Other Info",
        "contact_type": "Contact Type",
        "contact_frequency": "Contact Frequency",
        "importance": "Importance",
        "critical": "Critical",
        "note": "Note",
        "contact_records": "Contact Records",
        "view_all": "View All",
        "last_contact": "Last Contact",
        "not_contacted": "Not contacted",
        "next_contact": "Next Contact",
        "not_set": "Not set",
        "delete_contact": "Delete Contact",
        "add_tag": "Add Tag",
        "no_tags": "No tags",
        "related_goals": "Related Goals",
        "no_related_goals": "No related goals",
        
        "frequency_daily": "Daily",
        "frequency_weekly": "Weekly",
        "frequency_monthly": "Monthly",
        "frequency_quarterly": "Quarterly",
        "frequency_yearly": "Yearly",
        "frequency_occasional": "Occasional",
        "contacts_doctor": "Doctors",
        "contacts_lawyer": "Lawyers",
        "contacts_rich": "Rich",
        "contacts_official": "Officials",
        "contacts_gangster": "Gangsters",

        // 复合文案片段
        "delete_contact_confirm_before": "Are you sure you want to delete \"",
        "delete_contact_confirm_after": "\"? This action cannot be undone.",
        "restore_goal_confirm_before": "Are you sure to restore \"",
        "restore_goal_confirm_after": "\"?",
        "restore_contact_confirm_before": "Are you sure to restore \"",
        "restore_contact_confirm_after": "\"?",
        "permanent_delete_goal_confirm_before": "Are you sure to permanently delete \"",
        "permanent_delete_goal_confirm_after": "\"? This action cannot be undone.",
        "permanent_delete_contact_confirm_before": "Are you sure to permanently delete \"",
        "permanent_delete_contact_confirm_after": "\"? This action cannot be undone.",
        "action_cannot_be_undone": "This action cannot be undone.",
        "contact_log_feature": "Contact Log",
        "contact_log_description_before": "Record contact history with ",
        "contact_log_description_after": "",
        "name_empty": "Name cannot be empty",
        "name_min_length": "Name must be at least 2 characters",
        "invalid_email": "Please enter a valid email address",
        "goal_name_empty": "Goal name cannot be empty",
        "goal_name_min_length": "Goal name must be at least 2 characters",
        // Asset Center
        "my_assets": "My Assets",
        "asset_details": "Details",
        "asset_trend": "Trend",
        "asset_management": "Management",
        "total_assets": "Total Assets",
        "net_assets": "Net Assets",
        "cash": "Cash",
        "other_assets": "Other Assets",
        "debt": "Debt",
        "ten_thousand_unit": "ten-thousand",
        "time_range": "Time Range",
        "last_3_months": "Last 3 months",
        "last_6_months": "Last 6 months",
        "last_1_year": "Last 1 year",
        "record_history": "History",
        "asset_goal": "Asset Goal",
        "year_goal": "Yearly Goal",
        "completed_percent": "Completed",
        "days_left_year_prefix": "Days left this year: ",
        "days_unit": " days",
        "monthly_growth_goal": "Monthly Growth Goal",
        "current": "Current",
        "target": "Target",
        "adjust": "Adjust",
        "asset_tips_title": "Asset Tips",
        "asset_tip_1": "Update asset status monthly",
        "asset_tip_2": "Watch allocation balance",
        "asset_tip_3": "Evaluate returns and risks",
        "asset_tip_4": "Maintain cash reserves",
        "asset_tip_5": "Set reasonable growth goals",
        "asset_tip_6": "Keep debt under 30% of total assets",
        "save_changes": "Save Changes",
        "assets_updated": "Assets Updated",
        "assets_updated_message": "Your asset info has been saved",
        "add_asset_category": "Add Asset Category",
        "set_asset_goal": "Set Asset Goal",
        "export_asset_report": "Export Asset Report",
        // Achievement Center
        "achievement_center": "Achievement Center",
        "achievement_list": "Achievement List",
        "total_achievements": "Total Achievements",
        "unlock_rate": "Unlock Rate",
        // Anxiety Center
        "anxiety_center": "Anxiety Center",
        "anxiety_list": "Anxiety List",
        "total_anxiety": "Total Anxiety",
        "weekly_new": "Added in 7 days",
        "asset_allocation": "Asset Allocation",
        "monthly_avg_growth": "Monthly Avg Growth",
        "asset_cash_desc": "Savings and deposits",
        "asset_other_desc": "Stocks, funds, properties",
        "asset_debt_desc": "Credit cards, loans",
        // HomeView card context menu
        "move_position": "Move Position",
        "size_small_1x1": "Small 1×1",
        "size_medium_1x2": "Medium 1×2",
        "size_large_2x2": "Large 2×2",
        // RecordView menu actions
        "jump_to_today": "Jump to Today",
        "jump_to_this_week": "Jump to This Week",
        "jump_to_this_month": "Jump to This Month",
        "jump_to_this_quarter": "Jump to This Quarter",
        "jump_to_this_year": "Jump to This Year",
        "summarize_today_goals": "Summarize today's goal completion",
        "summarize_this_week": "Summarize This Week",
        "summarize_this_month": "Summarize This Month",
        "summarize_this_quarter": "Summarize This Quarter",
        "summarize_this_year": "Summarize This Year",
        "clear_daily": "Clear Daily",
        "clear_weekly": "Clear Weekly",
        "clear_monthly": "Clear Monthly",
        "clear_quarterly": "Clear Quarterly",
        "clear_yearly": "Clear Yearly",
        // Trash views
        "trash_empty_title": "Trash is empty",
        "deleted_goals_keep_days_prefix": "Deleted goals are kept here for ",
        "deleted_contacts_keep_days_prefix": "Deleted contacts are kept here for ",
        "restore_goal": "Restore Goal",
        "restore_contact": "Restore Contact",
        "restore": "Restore",
        "permanent_delete": "Delete Permanently",
        "deleted_on_prefix": "Deleted ",
        "days_until_permanent_delete_prefix": "Permanent deletion in ",
        "immediate_permanent_delete": "Permanent deletion imminent",
        "empty_trash_confirm_goal": "Emptying the trash will permanently delete all deleted goals. This action cannot be undone.",
        "empty_trash_confirm_contact": "Emptying the trash will permanently delete all deleted contacts. This action cannot be undone.",
        "clear": "Clear",
        "record_tab_recent": "Recent",
        "record_tab_daily": "Daily",
        "record_tab_weekly": "Weekly",
        "record_tab_monthly": "Monthly",
        "record_tab_quarterly": "Quarterly",
        "record_tab_yearly": "Yearly",
        // Habit Center
        "habit_center": "Habit Center",
        "home_card_habit_title": "Habits",
        "empty_no_habits": "No habits yet",
        "my_habits": "My Habits",
        "habit_goals": "Habit Goals",
        "no_habits": "No habits yet",
        "start_first_habit": "Start your first good habit",
        "unnamed_habit": "Unnamed Habit",
        "streak_days_prefix": "Streak ",
        "unnamed_goal": "Unnamed Goal",
        "progress_prefix": "Progress ",
        // Home cards titles
        "home_card_asset_title": "My Assets",
        "home_card_achievement_title": "Achievements",
        "home_card_anxiety_title": "Anxieties",
        // Tags management
        "my_tags": "My Tags",
        "start_first_record": "Start writing your first record",
        "no_mood": "No mood",
        "clear_goal_reference": "Clear Goal Reference",
        "clear_contact_reference": "Clear Contact Reference",
        "empty_no_achievements": "No achievements yet",
        "empty_no_pinned_subtasks": "No pinned subtasks yet",
        "unnamed_achievement": "Unnamed Achievement",
        "empty_no_anxiety": "No anxieties yet",
        "unnamed_anxiety": "Unnamed Anxiety",
        // Goal Detail module UI
        "please_select_content": "Please select content to edit",
        "unknown_edit_type": "Unknown edit type",
        "edit_goal_name": "Edit Goal Name",
        "edit_goal_description": "Edit Goal Description",
        "adjust_progress": "Adjust Progress",
        "add_upper_project": "Add Upper Project",
        "edit_upper_project": "Edit Upper Project",
        "add_sub_project": "Add Sub Project",
        "edit_sub_project": "Edit Sub Project",
        "edit_task": "Edit Task",
        "set_due_date": "Set Due Date",
        // Ping button
        "pin_to_home": "Pin to Home",
        "unpin_from_home": "Unpin from Home",
        "pinned_subtasks_title": "Pinned Subtasks",
        "pinned_subtasks_manage_title": "Pinned Subtasks",
        "task_status_all": "All",
        "task_status_in_progress": "In Progress",
        "task_status_done": "Done",
        "unpin": "Unpin",
        "pin_label": "Pin",
        "unpin_label": "Unpin",
        // Goal Detail Module additions
        "upper_project": "Upper Project",
        "sub_project": "Sub Project",
        "task_title": "Task Title",
        "enter_task_title": "Enter task title",
        "search_goal": "Search Goal",
        "selected_goals": "Selected Goals",
        "select_related_goals": "Select Related Goals",
        "character_count_format": "%d chars",
        "low_short": "Low",
        "medium_short": "Med",
        "high_short": "High",
        "tag_achievement": "Achievement",
        "tag_achievement_desc": "Tag your achievements, milestones, and important accomplishments to reflect and reinforce positive feedback.",
        "tag_anxiety": "Anxiety",
        "tag_anxiety_desc": "Tag things that make you anxious to identify stress sources and manage them.",
        "tag_category_system_built_in": "System Built-in",
        "tag_category_system_built_in_desc": "Default tags provided by the system for marking important types.",
        "choose_upper_project": "Choose Upper Project",
        "choose_sub_project": "Choose Sub Project",
        // Reminders integration
        "reminders": "Reminders",
        "needs_reminder_permission": "Reminders permission is required to import tasks",
        "new_task": "New Task",
        "imported_from_app": "Imported from Goal Manager",
        "import_success": "Task imported to Reminders",
        "import_failed_prefix": "Import failed: ",
        "sync_to_reminders": "Sync to Reminders",
        // Goal module top bar & filters
        "goals_plans": "Goals/Plans",
        "filtered_results": "Filtered results",
        "clear_filter": "Clear filter",
        "no_results": "No results",
        "year_suffix": "",
        "goal_filter": "Goal Filter",
        // Contact selector
        "selected_contacts": "Selected Contacts",
        "choose_contact": "Choose Contacts",
        // Background picker
        "preset_background": "Preset Background",
        "default_gradient": "Default Gradient",
        "recent_uploads": "Recent Uploads",
        "no_uploaded_images": "No uploaded images",
        "upload_custom_background_hint": "You can upload a custom background below",
        "custom_background": "Custom Background",
        "choose_from_album": "Choose from Photos",
        "use_this_image": "Use this image",
        "choose_background": "Choose Background",
        "confirm_action": "Confirm Action",
        "remove_from_list": "Remove from list",
        "remove_recent_upload_confirm_message": "Remove this image from Recent Uploads? The file is kept.",
        // Goal activity
        "goal_activity": "Goal Activity",
        "no_activity_logs": "No activity logs",
        "delete_log_confirm": "Delete this log? This cannot be undone.",
        // Home top bar
        "me": "Me",
        "diary": "Diary",
        // Activity log strings
        "unknown": "Unknown",
        "activity_create_format": "Created goal \"%@\"",
        "activity_name_change_format": "Renamed goal \"%@\" to \"%@\"",
        "activity_description_change_format": "Updated description for \"%@\"",
        "activity_progress_change_from_to_format": "Updated progress for \"%@\" from %@ to %@",
        "activity_progress_change_generic_format": "Updated progress for \"%@\"",
        "activity_type_change_from_to_format": "Changed type for \"%@\" from \"%@\" to \"%@\"",
        "activity_type_change_generic_format": "Changed type for \"%@\"",
        "activity_importance_change_from_to_format": "Changed importance for \"%@\" from %@ to %@",
        "activity_due_date_set_format": "Set due date for \"%@\" to %@",
        "activity_due_date_clear_format": "Cleared due date for \"%@\"",
        "activity_tag_add_format": "Added tag \"%@\" to \"%@\"",
        "activity_tag_remove_format": "Removed tag \"%@\" from \"%@\"",
        "activity_task_add_format": "Added task \"%@\" to \"%@\"",
        "activity_task_complete_format": "Completed task \"%@\" for \"%@\"",
        "activity_task_incomplete_format": "Marked task \"%@\" incomplete for \"%@\"",
        "activity_task_modify_format": "Renamed task \"%@\" to \"%@\" for \"%@\"",
        "activity_habit_checkin_format": "Habit check-in completed for \"%@\"",
        // Short messages for list items
        "activity_create_short": "Created goal",
        "activity_name_change_short": "Name changed",
        "activity_description_change_short": "Description updated",
        "activity_progress_change_short": "Progress updated",
        "activity_type_change_short": "Type changed",
        "activity_importance_change_short": "Importance changed",
        "activity_due_date_change_short": "Due date updated",
        "activity_tag_add_short": "Tag added",
        "activity_tag_remove_short": "Tag removed",
        "activity_task_add_short": "Task added",
        "activity_task_complete_short": "Task completed",
        "activity_task_incomplete_short": "Task marked incomplete",
        "activity_task_remove_short": "Task removed",
        "activity_task_modify_short": "Task renamed",
        "activity_contact_add_short": "Contact linked",
        "activity_contact_remove_short": "Contact unlinked"
    ]
}
